### PR TITLE
Spring 15Request

### PR DESCRIPTION
**Pull request by An4ik**
Pachacha

### CODE REVIEW

**Comment by giAtSDU** [comment]
@An4ik Good Work!

**Comment by giAtSDU** [comment]
@An4ik Did you do merge with `conflict` branch?

**Comment by An4ik** [comment]
Hello) yes teacher ) ! I have done it ! There were conflict with filese
README.md   and server.py!     there were names     BIEBER, OBAMA etc.

2015-02-13 12:51 GMT+06:00 German Ilyin notifications@github.com:

**Comment by giAtSDU** [comment]
@An4ik where is your merge commit then?

**Pull request closed without merging**
